### PR TITLE
update build

### LINKED ISSUE #113: WOF remap misc properties
This change https://github.com/whosonfirst-data/whosonfirst-data/pull/979 will require some minor edits to ensure the `photo_sum` property is being correctly imported.

### PR DESCRIPTION
**Pull request by missinglink**
This PR simply refreshes the data to a download from July '18

I would like to merge this ahead of the other PRs which add/change functionality.

fixes https://github.com/pelias/placeholder/issues/113

### CODE REVIEW

**Comment by missinglink** [comment]
data uploaded:

```
$ AWS_PROFILE=nextzen aws s3 ls s3://pelias-data.nextzen.org/placeholder/archive/2018-07-09/
2018-07-09 18:19:05  366964135 store.sqlite3.gz
2018-07-09 18:21:13  106799480 wof.extract.gz
```

**Comment by missinglink** [comment]
build promoted to production

```
--- promoting build to production ---
copy: s3://pelias-data.nextzen.org/placeholder/archive/2018-07-09/store.sqlite3.gz to s3://pelias-data.nextzen.org/placeholder/store.sqlite3.gz
copy: s3://pelias-data.nextzen.org/placeholder/archive/2018-07-09/wof.extract.gz to s3://pelias-data.nextzen.org/placeholder/wof.extract.gz
--- list remote production files ---
                           PRE archive/
                           PRE master/
                           PRE production/
                           PRE staging/
2018-07-09 18:36:17  350.0 MiB store.sqlite3.gz
2018-07-09 18:36:32  101.9 MiB wof.extract.gz
```

**Comment by orangejulius** [comment]
Will the data now on S3 work without the changes merged in this PR? If not, no big deal, i'll merge master ->staging ->prod

**Comment by missinglink** [comment]
This PR should be 100% backwards compatible, so it should be fine on older versions of the code.

There is a check at startup which ensures the schema in the database matches what is expected by the code, so it would fail loud and early if there were a mismatch (which there isn't here).

The staging->prod workflow doesn't really make sense for this repo as it contains all it's unit tests and functional tests internally within the repo, so all acceptance testing is performed in CI prior to merging to master.

**Comment by missinglink** [comment]
That being said, there was also one bugfix in this PR which should make it's way to all the branches as soon as possible.

**Pull request merged**
