### PR TITLE
fix: Inconsistent iso codes in wof (iso639-2T and iso639-2B)

### PR DESCRIPTION
**Pull request by Joxit**
Workaround to fix this in placeholder.
See https://github.com/whosonfirst-data/whosonfirst-data/issues/1282

### CODE REVIEW

**Comment by missinglink** [comment]
Looks like a good workaround for the data issue in WOF.

I am wondering if we should be doing the data correction when building the database rather than when querying it?

As it is, we might need to copy that code to cover other endpoints such as `findbyid`.

If we patch the data when creating the database then the db will contain corrected data and all the other APIs will 'just work'.

**Comment by Joxit** [comment]
Hum, yes you are right, I will change this and do the patch when creating the database.

**Comment by Joxit** [comment]
Updated.
I'm a little scared of the case where both iso are used as for Europe [102191581](https://spelunker.whosonfirst.org/id/102191581/) (`fra` and `fre` are present).
Theoretically it should not have problems because they will have the same translation.

**Comment by missinglink** [comment]
Looks good, sorry to be annoying but could we please also add:

- a code comment explaining the need for this, and suggesting that it can be removed once the source data is fixed, and link to the WOF issue. It could probably just link here for simplicity?
- One or two test cases which involve accessing the `alternatives.js` map and ensuring it works as expected.

Other than that, happy to merge :)

**Comment by missinglink** [comment]
Re: the case where both schemes are available (`fra` & `fre`), we should really favour the 'correct one' if present.

That's the T code, right?

Although doing that might make the code a bit messier, what do you think?

**Review by missinglink — APPROVED** [review]
pre-approving

**Comment by Joxit** [comment]
Ok, I will do that :) 

Yes, we should select the "correct one" when it's present, but this will make the code a bit more complicated. I will do my best ;)

**Comment by Joxit** [comment]
Done, finally it does not make the code more complicated

**Comment by missinglink** [comment]
I bundled this release with an updated copy of the whosonfirst data current 08.08.2018

```bash
$ AWS_PROFILE=nextzen ./cmd/s3_upload.sh
--- gzipping data files ---
--- uploading archive ---
upload: data/store.sqlite3.gz to s3://pelias-data.nextzen.org/placeholder/archive/2018-08-17/store.sqlite3.gz
upload: data/wof.extract.gz to s3://pelias-data.nextzen.org/placeholder/archive/2018-08-17/wof.extract.gz
--- list remote archive ---
2018-08-17 15:25:07  355.5 MiB store.sqlite3.gz
2018-08-17 15:25:12  101.2 MiB wof.extract.gz

> would you like to promote this build to production (yes/no)?
yes
--- promoting build to production ---
copy: s3://pelias-data.nextzen.org/placeholder/archive/2018-08-17/store.sqlite3.gz to s3://pelias-data.nextzen.org/placeholder/store.sqlite3.gz
copy: s3://pelias-data.nextzen.org/placeholder/archive/2018-08-17/wof.extract.gz to s3://pelias-data.nextzen.org/placeholder/wof.extract.gz
--- list remote production files ---
                           PRE archive/
                           PRE master/
                           PRE production/
                           PRE staging/
2018-08-17 15:25:17  355.5 MiB store.sqlite3.gz
2018-08-17 15:25:19  101.2 MiB wof.extract.gz
```

**Comment by missinglink** [comment]
all tests passing, merging

**Comment by missinglink** [comment]
Thanks @Joxit! The updated database should now be available in the s3 bucket at the usual location.

**Comment by Joxit** [comment]
Nice! That's cool thanks :)

**Pull request merged**
