### PR TITLE
fix(wof:extract): ensure grep filter always returns a happy status code

### LINKED ISSUE #38: Export skips files
While working on the docker-compose setup for Pelias, I came across this odd behavior and was able to confirm it outside of docker as well.

Here's a script I've used to reproduce it:

```bash
#!/bin/bash

mkdir -p ./test_build && cd ./test_build

git clone https://github.com/pelias/whosonfirst.git ./whosonfirst && cd ./whosonfirst;

git checkout filtered-download

npm install

echo \
'{
  "imports":{
    "whosonfirst": {
      "datapath": "../data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "101715829",
      "api_key": "mapzen-fepXwQF"
    }
  }
}' > pelias.json

PELIAS_CONFIG=pelias.json npm run download

cd ..

git clone https://github.com/pelias/placeholder.git ./placeholder && cd ./placeholder;

npm install

mkdir -p ./data

WOF_DIR=../data/whosonfirst npm run extract

npm run build

echo "\033[31mCounts don't match up: \033[m"

find ../data/whosonfirst/data/ -name "*.geojson" | wc -l | awk '{print $1" wof records available"}'

wc -l ./data/wof.extract | awk '{print $1" lines in export"}'
```

in the end I'm getting the following counts consistently:

```
Counts don't match up: 
140 wof records available
33 lines in export
```

I've confirmed that the skipped WOF records are valid geojson files, so it's unclear why they are being skipped. Unfortunately, I couldn't make much sense of the *bash kung-fu* happening in wof_extract.sh.

### PR DESCRIPTION
**Pull request by missinglink**
resolves https://github.com/pelias/placeholder/issues/38

### CODE REVIEW

**Comment by dianashk** [comment]
Ran it again locally and now I'm getting an error instead of it pretending everything is ok. Counts still don't match up.

```
> pelias-placeholder@0.0.0-semantic-release extract /Users/diana/Code/placeholder/test_build/placeholder
> bash cmd/wof_extract.sh > data/wof.extract

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/diana/.nvm/versions/node/v4.0.0/bin/node" "/Users/diana/.nvm/versions/node/v4.0.0/bin/npm" "run" "extract"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! pelias-placeholder@0.0.0-semantic-release extract: `bash cmd/wof_extract.sh > data/wof.extract`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-placeholder@0.0.0-semantic-release extract script 'bash cmd/wof_extract.sh > data/wof.extract'.

...

> pelias-placeholder@0.0.0-semantic-release build /Users/diana/Code/placeholder/test_build/placeholder
> rm -f data/graph.json data/store.sqlite3; cat data/wof.extract | node cmd/load.js

importing...
nodes 242
edges 10
sorting...
vacuuming sqlite db...
saving...
Counts don't match up: 
140 wof records available
33 lines in export
```

**Comment by missinglink** [comment]
hmm.. that's odd because I tested it and it worked for me, it's possible that the `grep` command on OSX behaves differently, although I'm not sure how exactly.

could you please just do a sanity check that you're on the correct branch? try `rf data/wof.extract` first and then instead of running `npm run extract` try running it manually with `bash cmd/wof_extract.sh > data/wof.extract` and see if that makes any difference.

**Comment by missinglink** [comment]
```bash
peter: .../pelias/placeholder (issue-38 $)$ rm data/wof.extract
peter: .../pelias/placeholder (issue-38 $)$ WOF_DIR=/tmp/wof npm run extract

> pelias-placeholder@0.0.0-semantic-release extract /var/www/pelias/placeholder
> bash cmd/wof_extract.sh > data/wof.extract

info: using parallel execution
peter: .../pelias/placeholder (issue-38 $)$ echo $?
0
peter: .../pelias/placeholder (issue-38 $)$ wc -l data/wof.extract
114 data/wof.extract
```

I also tried it without using the `parallel` command and it worked the same (I noticed you don't have it installed because it outputs a line `info: using parallel execution`).

**Comment by dianashk** [comment]
Sorry, you are totally right! I checked out the branch of placeholder where I was running the test, but not in the script. Durp! 😬

It works great with the proper branch. It's good to merge.

**Review by dianashk — APPROVED** [review]

**Pull request merged**
