### PR TITLE
Streamline documentation

### PR DESCRIPTION
**Pull request by orangejulius**
This is a reorganizing of the Placeholder documentation with the goal
of allowing for new users to quickly understand the need for, and how to
install, Placeholder.

To that end, the initial description and installation instructions have
been made more concise, with the more detailed info moved further down
in the readme.

Additionally, capitalization has been fixed.

### CODE REVIEW

**Comment by orangejulius** [comment]
Looking for feedback on those first couple sentences. It's tough to describe accurately, simply, and concisely what Placeholder does. I'm sure there's room for improvement.

**Comment by missinglink** [comment]
I thought my description was good :(

I actually got positive feedback from a few people about it so I'm a bit surprised you would like to replace it.

**Comment by missinglink** [comment]
I can see how a more concise introduction might be useful, but I think the existing copy (In this PR) needs some reworking to achieve that goal :)

**Comment by tigerlily-he** [comment]
The new description covers how Placeholder 
> ensures token groups represent geographic entities contained *within* those which came before

but skips over the tokenization part of determining "Paris Texas United States" is split into [Paris][Texas][United States]. 

Laying out the two examples in unstructured text form before explaining what placeholder does would show the tokenization step.

For example, "Consider the following unstructured input text: (1) 'Paris France' and (2) 'Paris Texas United States'. Placeholder determines that the first contains two tokens [Paris][France] and the second contains three tokens [Paris][Texas][United States] (and not two [Paris Texas][United States] or four tokens [Paris][Texas][United][States]".

**Comment by orangejulius** [comment]
@missinglink your description _is_ good. The idea of this change is to break up the initial wall of text and provide a structure to the README that starts simple and adds detail. I'm thinking the following format is ideal:

- one sentence description of the problem placeholder solves

- one or two sentences with examples (the ones from @tigerlily-he are great)

- very concise quick-start installation instructions

- extended descriptions, configuration, installation details, etc

**Comment by missinglink** [comment]
I think this PRs has been somewhat superceded by https://github.com/pelias/placeholder/pull/187.

Due to the age of this PR I'm going to close it, the README still isn't perfect, so maybe we can extract any parts of this which are still valuable and merge them in another PR?

**Pull request closed without merging**
