### PR TITLE
feat(wof_extract) Remove dependency on gnu parallel

### LINKED ISSUE #44: remove dependency on gnu parallel
re: https://github.com/pelias/placeholder/blob/master/cmd/wof_extract.sh#L27-L44

apparently `xargs` supports parallel execution natively by passing it a parallel flag, so we can get rid of our external dependency on `parallel`

### PR DESCRIPTION
**Pull request by Joxit**
This closes #44

### CODE REVIEW

**Comment by missinglink** [comment]
hey @Joxit, I've recently switched to a mac for my development laptop, and a bunch of other developers use a mac too, could we please change the CPU detection code to something more portable?

I've found `getconf _NPROCESSORS_ONLN` works well across POSIX-style systems.

**Comment by missinglink** [comment]
```bash
➜  ~ grep -c '^processor' /proc/cpuinfo
grep: /proc/cpuinfo: No such file or directory
➜  ~ getconf _NPROCESSORS_ONLN
8
```

**Comment by Joxit** [comment]
Thanks for your review :) I've updated the code

**Comment by orangejulius** [comment]
This worked great for me :)

**Comment by missinglink** [comment]
I didn't have time to test it yet, if you've confirmed it works @orangejulius then it can be merged.

**Pull request merged**
